name: Unit Tests

on:
  pull_request:
    branches:
      - main # Adjust the branch name if needed

jobs:
  tests:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [18.x, 16.x]
      
    steps:
      - uses: actions/checkout@v2
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v1
        with:
          node-version: ${{ matrix.node-version }}
      - name: npm install
        run: npm ci
      - name: Run tests and collect results
        id: test
        run: |
          if npm test; then
            echo "All tests passed"
            echo "::set-output name=tests-passed::true"
          else
            echo "Tests failed"
            echo "::set-output name=tests-passed::false"
          fi
      - name: Set PR status
        if: ${{ steps.test.outputs.tests-passed == 'false' }}
        uses: marocchino/sticky-pull-request-comment@v2
        with:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          message: "Tests failed. Please fix failing tests before merging."
